[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ptychodus"
description = "Ptychodus is a ptychography data pipeline application."
readme = "README.rst"
requires-python = ">=3.11"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
dependencies = [
    "colorcet",
    "h5py>=3",
    "hdf5plugin",
    "matplotlib",
    "numpy",
    "psutil",
    "pydantic",
    "pyyaml",
    "requests",
    "scikit-image",
    "scipy",
    "tifffile",
    "watchdog",
]
dynamic = ["version"]

[project.scripts]
convert-to-ptychodus = "ptychodus.convert_to_ptychodus:main"
ptychodus = "ptychodus.__main__:main"
ptychodus-bdp = "ptychodus.ptychodus_bdp:main"
ptychodus-ptychopinn-tf-test = "ptychodus.scripts.ptychopinn_tf_test:main"
ptychodus-set-iri-tokens = "ptychodus.model.genesis.iri:set_iri_tokens_cli"
ptychodus-check-iri-tokens = "ptychodus.model.genesis.iri:check_iri_tokens_cli"
ptychodus-set-transfer-tokens = "ptychodus.model.genesis.transfer:set_transfer_tokens_cli"
ptychodus-check-transfer-tokens = "ptychodus.model.genesis.transfer:check_transfer_tokens_cli"

[project.optional-dependencies]
globus = ["globus-compute-sdk", "globus-sdk>=4.5.0"]
gui = ["PyQt5"]
#ptychonn = ["ptychonn==0.3.*,>=0.3.7"]
ptychi = ["ptychi==1.*,>=1.2.0"]
ptychopinn = ["ptychopinn[torch]"]

[tool.uv.sources]
ptychopinn = { path = "../PtychoPINN", editable = true }
#ptychopinn = { git = "https://github.com/hoidn/PtychoPINN", branch = "torchapi-devel" }

[tool.setuptools.package-data]
"ptychodus" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]

[[tool.mypy.overrides]]
module = [
    "colorcet",
    "globus_sdk.*",
    "h5py",
    "hdf5plugin",
    "lightning",
    "ptychi.*",
    "ptycho.*",
    "ptycho_torch.*",
    "ptychonn.*",
    "pvaccess",
    "pvapy.*",
    "scipy.*",
    "tifffile",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "F",
    "N",
    "NPY",
]

[tool.pyright]
pythonVersion = "3.11"

[dependency-groups]
dev = [
    "mypy",
    "pyqt5-stubs",
    "pytest",
    "ruff",
    "types-psutil",
    "types-pyyaml",
    "types-requests",
]
